# Generated by Django 3.1.3 on 2021-06-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210616_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
